spring:
  datasource:
    admin:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.100.127:3306/lsb_admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: xinyunlian_admin
      password: 12345678
    shop:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.100.127:3306/lsb_new?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: xinyunlian_admin
      password: 12345678
  mybatis:
    admin:
      configuration: classpath:mybatis/admin/configuration.xml
      #mappers: classpath:mybatis/admin/mappers/ADMShopMapper.xml
      typeAlias: com.xinyunlian.retailterminal.shop.database.model.admin
    shop:
      configuration: classpath:mybatis/shop/configuration.xml
      #mappers: classpath:mybatis/shop/mappers/*.xml
      typeAlias: com.xinyunlian.retailterminal.shop.database.model.shop

eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.200.25:9100/eureka/,http://192.168.200.206:9100/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}